import argparse
import csv
import json
import re
import time
from collections import defaultdict, deque
from datetime import datetime
from pathlib import Path

import cv2
import numpy as np
import supervision as sv
import torch
from ultralytics import YOLO

from models import build_model
from video_analyzer import (
    COCO_VEHICLE_CLASS_IDS,
    DashboardState,
    MODEL_PATH,
    VEHICLE_TYPE_BY_COCO_ID,
    VehicleState,
    assign_points_to_regions,
    calculate_annotation_style,
    calculate_region_risks,
    create_output_dir,
    estimate_velocity_mps,
    format_label_float,
    heading_angle_rad,
    load_calibration,
    make_annotated_frame,
    make_empty_detections,
    print_progress,
    render_traffic_dashboard,
    resolve_existing_path,
    safe_name,
)


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_OUTPUT_ROOT = PROJECT_ROOT / "demo_outputs"
ANCHOR_CHOICES = sv.Position.list()


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="End-to-end live demo: vision measurement, mechanism risk and temporal prediction."
    )
    parser.add_argument(
        "--source-video-path",
        required=True,
        help="Path to the source video.",
    )
    parser.add_argument(
        "--calibration-path",
        required=True,
        help="Path to calibration JSON generated by labeling.py.",
    )
    parser.add_argument(
        "--temporal-model-path",
        required=True,
        help="Path to best_model.pt generated by train.py.",
    )
    parser.add_argument(
        "--output-root",
        default=str(DEFAULT_OUTPUT_ROOT),
        help="Root directory for demo outputs.",
    )
    parser.add_argument(
        "--anchor",
        default="CENTER",
        choices=ANCHOR_CHOICES,
        help="Detection anchor used for vehicle position and motion estimation.",
    )
    parser.add_argument("--speed-window-seconds", default=1.0, type=float)
    parser.add_argument("--speed-smoothing-seconds", default=0.5, type=float)
    parser.add_argument("--risk-alpha", default=1.5, type=float)
    parser.add_argument("--risk-beta", default=1.0, type=float)
    parser.add_argument("--risk-horizon-seconds", default=10.0, type=float)
    parser.add_argument("--same-direction-degrees", default=30.0, type=float)
    parser.add_argument("--min-risk-speed-mps", default=0.5, type=float)
    parser.add_argument("--lateral-longitudinal-gate-m", default=12.0, type=float)
    parser.add_argument(
        "--window-size",
        default=None,
        type=int,
        help="Temporal window size. Defaults to training_metadata.json sequence_length or 60.",
    )
    parser.add_argument("--display-width", default=960, type=int)
    parser.add_argument("--threshold", default=None, type=float)
    parser.add_argument("--device", default="auto", choices=["auto", "cpu", "cuda"])
    parser.add_argument("--no-show", action="store_true")
    parser.add_argument("--save-video", action="store_true")
    parser.add_argument(
        "--no-dashboard",
        action="store_true",
        help="Disable the smart-traffic monitoring dashboard layout.",
    )
    parser.add_argument("--dashboard-width", default=1600, type=int)
    parser.add_argument("--dashboard-height", default=900, type=int)
    return parser.parse_args()


def choose_device(device_arg: str) -> torch.device:
    if device_arg == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA was requested but is not available.")
        return torch.device("cuda")
    if device_arg == "auto" and torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def load_training_metadata(model_path: Path) -> dict:
    metadata_path = model_path.parent / "training_metadata.json"
    if not metadata_path.exists():
        return {}
    with metadata_path.open("r", encoding="utf-8") as file:
        return json.load(file)


def load_temporal_model(
    model_path: Path,
    device: torch.device,
) -> tuple[torch.nn.Module, dict, dict]:
    checkpoint = torch.load(model_path, map_location=device)
    training_metadata = load_training_metadata(model_path)
    model_name = checkpoint.get("model_name") or training_metadata.get("model", "lstm")
    input_size = int(checkpoint["input_size"])
    model = build_model(
        name=model_name,
        input_size=input_size,
        hidden_size=int(checkpoint.get("hidden_size", 64)),
        num_layers=int(checkpoint.get("num_layers", 2)),
        dropout=float(checkpoint.get("dropout", 0.1)),
    ).to(device)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()
    return model, checkpoint, training_metadata


def infer_window_size(
    args: argparse.Namespace,
    checkpoint: dict,
    training_metadata: dict,
) -> int:
    if args.window_size is not None:
        return args.window_size
    if "sequence_length" in checkpoint:
        return int(checkpoint["sequence_length"])
    if "sequence_length" in training_metadata:
        return int(training_metadata["sequence_length"])
    return 60


def feature_value(region_risk, feature_name: str) -> float:
    max_pair_probability = 0.0
    max_pair_type = ""
    if region_risk.max_pair is not None:
        max_pair_probability = region_risk.max_pair.probability
        max_pair_type = region_risk.max_pair.risk_type

    mapping = {
        "区域瞬时事故概率P_A(t)": region_risk.probability,
        "车流密度rho(t)（veh/m^2）": region_risk.density,
        "区域车辆数N(t)": region_risk.vehicle_count,
        "有效风险车辆数": region_risk.valid_vehicle_count,
        "最大单车风险P_i(t)": region_risk.max_vehicle_probability,
        "最大车辆对风险P_ij(t)": max_pair_probability,
        "risk_type_long": 1.0 if max_pair_type == "long" else 0.0,
        "risk_type_lat": 1.0 if max_pair_type == "lat" else 0.0,
    }
    return float(mapping.get(feature_name, 0.0))


def build_feature_vector(region_risk, feature_columns: list[str]) -> np.ndarray:
    return np.array(
        [feature_value(region_risk, column) for column in feature_columns],
        dtype=np.float32,
    )


def predict_region_risk(
    model: torch.nn.Module,
    window: deque[np.ndarray],
    mean: np.ndarray,
    std: np.ndarray,
    device: torch.device,
) -> float | None:
    if len(window) < window.maxlen:
        return None
    sequence = np.stack(list(window)).astype(np.float32)
    sequence = (sequence - mean) / std
    tensor = torch.from_numpy(sequence).unsqueeze(0).to(device)
    with torch.no_grad():
        probability = torch.sigmoid(model(tensor)).cpu().item()
    return float(probability)


def draw_temporal_prediction_blocks(
    frame: np.ndarray,
    predictions: dict[str, float | None],
    regions,
    threshold: float,
) -> np.ndarray:
    annotated = frame.copy()
    font = cv2.FONT_HERSHEY_SIMPLEX
    frame_height, frame_width = annotated.shape[:2]
    font_scale = max(0.95, min(frame_width / 1100.0, 1.35))
    small_font_scale = font_scale * 0.72
    thickness = max(2, int(round(font_scale * 2.4)))
    padding_x = int(round(14 * font_scale))
    padding_y = int(round(10 * font_scale))
    line_gap = int(round(10 * font_scale))

    for region in regions:
        polygon = region.source_polygon
        anchor_x = int(np.mean(polygon[:, 0]))
        anchor_y = int(np.min(polygon[:, 1]))
        probability = predictions.get(region.region_id)
        if probability is None:
            title_line = f"{region.region_id} FUTURE RISK"
            value_line = "warming up"
            color = (70, 70, 70)
        else:
            status = "HIGH" if probability >= threshold else "normal"
            title_line = f"{region.region_id} FUTURE RISK"
            value_line = f"Y = {probability * 100:.1f}%  {status}"
            color = (35, 35, 220) if probability >= threshold else (45, 130, 45)

        (title_width, title_height), _ = cv2.getTextSize(
            title_line,
            font,
            small_font_scale,
            thickness,
        )
        (value_width, value_height), _ = cv2.getTextSize(
            value_line,
            font,
            font_scale,
            thickness,
        )
        panel_width = max(title_width, value_width) + padding_x * 2
        panel_height = title_height + value_height + line_gap + padding_y * 2
        panel_x1 = max(0, min(anchor_x - panel_width // 2, frame_width - panel_width - 1))
        panel_y1 = max(0, min(anchor_y + 30, frame_height - panel_height - 1))
        panel_x2 = panel_x1 + panel_width
        panel_y2 = panel_y1 + panel_height

        overlay = annotated.copy()
        cv2.rectangle(overlay, (panel_x1, panel_y1), (panel_x2, panel_y2), color, -1)
        cv2.addWeighted(overlay, 0.82, annotated, 0.18, 0, annotated)
        cv2.rectangle(
            annotated,
            (panel_x1, panel_y1),
            (panel_x2, panel_y2),
            (255, 255, 255),
            2,
        )
        cv2.putText(
            annotated,
            title_line,
            (panel_x1 + padding_x, panel_y1 + padding_y + title_height),
            font,
            small_font_scale,
            (255, 255, 255),
            thickness,
            cv2.LINE_AA,
        )
        cv2.putText(
            annotated,
            value_line,
            (
                panel_x1 + padding_x,
                panel_y1 + padding_y + title_height + line_gap + value_height,
            ),
            font,
            font_scale,
            (255, 255, 255),
            thickness,
            cv2.LINE_AA,
        )
    return annotated


def create_demo_output_dir(source_video_path: Path, output_root: Path) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_dir = output_root / f"{timestamp}_{safe_name(source_video_path.stem)}_demo"
    output_dir.mkdir(parents=True, exist_ok=False)
    return output_dir


def write_metadata(
    output_dir: Path,
    args: argparse.Namespace,
    feature_columns: list[str],
    window_size: int,
    threshold: float,
) -> None:
    metadata = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "args": vars(args),
        "feature_columns": feature_columns,
        "window_size": window_size,
        "threshold": threshold,
    }
    with (output_dir / "demo_metadata.json").open("w", encoding="utf-8") as file:
        json.dump(metadata, file, ensure_ascii=False, indent=2)


def main() -> None:
    args = parse_arguments()
    source_video_path = resolve_existing_path(args.source_video_path)
    calibration_path = resolve_existing_path(args.calibration_path)
    temporal_model_path = resolve_existing_path(args.temporal_model_path)
    if not source_video_path.exists():
        raise FileNotFoundError(f"Source video not found: {source_video_path}")
    if not calibration_path.exists():
        raise FileNotFoundError(f"Calibration JSON not found: {calibration_path}")
    if not temporal_model_path.exists():
        raise FileNotFoundError(f"Temporal model not found: {temporal_model_path}")

    device = choose_device(args.device)
    temporal_model, checkpoint, training_metadata = load_temporal_model(
        temporal_model_path,
        device,
    )
    feature_columns = checkpoint.get("feature_columns") or training_metadata.get(
        "feature_columns",
        [],
    )
    if not feature_columns:
        raise ValueError("The temporal model checkpoint does not contain feature_columns.")

    feature_mean = np.array(checkpoint.get("feature_mean", []), dtype=np.float32)
    feature_std = np.array(checkpoint.get("feature_std", []), dtype=np.float32)
    if len(feature_mean) != len(feature_columns) or len(feature_std) != len(feature_columns):
        raise ValueError("The temporal model checkpoint has invalid feature normalization data.")
    feature_std = np.where(feature_std < 1e-6, 1.0, feature_std).astype(np.float32)
    window_size = infer_window_size(args, checkpoint, training_metadata)
    threshold = float(args.threshold if args.threshold is not None else checkpoint.get("threshold", 0.5))

    regions = load_calibration(calibration_path)
    video_info = sv.VideoInfo.from_video_path(str(source_video_path))
    output_dir = create_demo_output_dir(source_video_path, Path(args.output_root))
    prediction_csv_path = output_dir / f"{safe_name(source_video_path.stem)}_demo_predictions.csv"
    write_metadata(output_dir, args, feature_columns, window_size, threshold)

    yolo_model = YOLO(str(MODEL_PATH))
    anchor = sv.Position(args.anchor)
    byte_track = sv.ByteTrack(frame_rate=video_info.fps)
    thickness, text_scale = calculate_annotation_style(
        resolution_wh=video_info.resolution_wh,
        display_width=args.display_width,
    )
    box_annotator = sv.BoxAnnotator(thickness=thickness)
    label_annotator = sv.LabelAnnotator(
        text_scale=text_scale,
        text_thickness=thickness,
        text_position=sv.Position.BOTTOM_CENTER,
    )
    trace_annotator = sv.TraceAnnotator(
        thickness=thickness,
        trace_length=int(video_info.fps * 2),
        position=anchor,
        color_lookup=sv.ColorLookup.TRACK,
    )
    source_polygons = [region.source_polygon for region in regions]
    use_dashboard = not args.no_dashboard
    dashboard_state = DashboardState(maxlen=max(60, int(round(video_info.fps * 12))))
    output_resolution_wh = (
        (args.dashboard_width, args.dashboard_height)
        if use_dashboard
        else video_info.resolution_wh
    )

    speed_window_frames = max(2, round(video_info.fps * args.speed_window_seconds))
    smoothing_frames = max(2, round(video_info.fps * args.speed_smoothing_seconds))
    coordinate_history = defaultdict(lambda: deque(maxlen=speed_window_frames))
    velocity_history = defaultdict(lambda: deque(maxlen=smoothing_frames))
    previous_smoothed_velocity = {}
    feature_windows = {
        region.region_id: deque(maxlen=window_size)
        for region in regions
    }

    video_writer = None
    if args.save_video:
        annotated_video_path = output_dir / f"{safe_name(source_video_path.stem)}_demo.mp4"
        fourcc = cv2.VideoWriter_fourcc(*"mp4v")
        video_writer = cv2.VideoWriter(
            str(annotated_video_path),
            fourcc,
            video_info.fps,
            output_resolution_wh,
        )

    frame_generator = sv.get_video_frames_generator(str(source_video_path))
    rows_written = 0
    total_frames = getattr(video_info, "total_frames", None)
    start_time = time.perf_counter()

    with prediction_csv_path.open("w", newline="", encoding="utf-8-sig") as file:
        writer = csv.DictWriter(
            file,
            fieldnames=[
                "video_id",
                "frame_id",
                "timestamp_s",
                "region_id",
                "instant_risk_P_A_t",
                "future_risk_probability",
                "alert",
                "window_ready",
            ],
        )
        writer.writeheader()

        for frame_id, frame in enumerate(frame_generator):
            timestamp_s = frame_id / video_info.fps
            result = yolo_model(frame, verbose=False)[0]
            detections = sv.Detections.from_ultralytics(result)
            if len(detections) > 0:
                vehicle_mask = np.isin(detections.class_id, list(COCO_VEHICLE_CLASS_IDS))
                detections = detections[vehicle_mask]
                detections = byte_track.update_with_detections(detections=detections)
            if detections.tracker_id is None:
                detections = make_empty_detections()

            image_points = detections.get_anchors_coordinates(anchor=anchor)
            keep_mask, assigned_regions, road_points = assign_points_to_regions(
                image_points=image_points,
                regions=regions,
            )
            if len(detections) > 0:
                detections = detections[keep_mask]
                image_points = image_points[keep_mask]

            labels = []
            state_label_blocks = []
            vehicle_states = []
            for index, (bbox, class_id, tracker_id, region) in enumerate(
                zip(
                    detections.xyxy,
                    detections.class_id,
                    detections.tracker_id,
                    assigned_regions,
                )
            ):
                road_x, road_y = road_points[index]
                vehicle_id = int(tracker_id)
                class_id = int(class_id)
                vehicle_type = VEHICLE_TYPE_BY_COCO_ID.get(class_id, "other_vehicle")
                history_key = (region.region_id, vehicle_id)
                coordinate_history[history_key].append(
                    (timestamp_s, float(road_x), float(road_y))
                )
                velocity = estimate_velocity_mps(coordinate_history[history_key])
                smoothed_vx = None
                smoothed_vy = None
                acceleration_x = None
                acceleration_y = None
                heading_rad = None
                if velocity is not None:
                    velocity_x, velocity_y = velocity
                    velocity_history[history_key].append((timestamp_s, velocity_x, velocity_y))
                    smoothed_vx = float(np.mean([vx for _, vx, _ in velocity_history[history_key]]))
                    smoothed_vy = float(np.mean([vy for _, _, vy in velocity_history[history_key]]))
                    heading_rad = heading_angle_rad(smoothed_vx, smoothed_vy)
                    previous = previous_smoothed_velocity.get(history_key)
                    if previous is not None:
                        previous_time, previous_vx, previous_vy = previous
                        elapsed = timestamp_s - previous_time
                        if elapsed > 0:
                            acceleration_x = (smoothed_vx - previous_vx) / elapsed
                            acceleration_y = (smoothed_vy - previous_vy) / elapsed
                    previous_smoothed_velocity[history_key] = (
                        timestamp_s,
                        smoothed_vx,
                        smoothed_vy,
                    )

                vehicle_states.append(
                    VehicleState(
                        region=region,
                        vehicle_id=vehicle_id,
                        x=float(road_x),
                        y=float(road_y),
                        vx=smoothed_vx,
                        vy=smoothed_vy,
                        ax=acceleration_x,
                        ay=acceleration_y,
                        theta=heading_rad,
                        class_id=class_id,
                    )
                )
                labels.append(
                    f"{vehicle_type}\n"
                    f"vx={format_label_float(smoothed_vx)} m/s\n"
                    f"vy={format_label_float(smoothed_vy)} m/s"
                )
                state_label_blocks.append(
                    [
                        f"region = {region.region_id}",
                        f"x_i(t) = {format_label_float(float(road_x))} m",
                        f"y_i(t) = {format_label_float(float(road_y))} m",
                        f"v_ix(t) = {format_label_float(smoothed_vx)} m/s",
                        f"v_iy(t) = {format_label_float(smoothed_vy)} m/s",
                        f"a_ix(t) = {format_label_float(acceleration_x)} m/s^2",
                        f"a_iy(t) = {format_label_float(acceleration_y)} m/s^2",
                        f"theta_i(t) = {format_label_float(heading_rad, 2)} rad",
                        f"c_i = {class_id}",
                    ]
                )

            region_risks = calculate_region_risks(
                regions=regions,
                vehicle_states=vehicle_states,
                alpha=args.risk_alpha,
                beta=args.risk_beta,
                risk_horizon_s=args.risk_horizon_seconds,
                same_direction_degrees=args.same_direction_degrees,
                min_speed_mps=args.min_risk_speed_mps,
                lateral_longitudinal_gate_m=args.lateral_longitudinal_gate_m,
            )

            predictions = {}
            for region_risk in region_risks:
                feature_windows[region_risk.region.region_id].append(
                    build_feature_vector(region_risk, feature_columns)
                )
                prediction = predict_region_risk(
                    model=temporal_model,
                    window=feature_windows[region_risk.region.region_id],
                    mean=feature_mean,
                    std=feature_std,
                    device=device,
                )
                predictions[region_risk.region.region_id] = prediction
                writer.writerow(
                    {
                        "video_id": source_video_path.stem,
                        "frame_id": frame_id,
                        "timestamp_s": f"{timestamp_s:.3f}",
                        "region_id": region_risk.region.region_id,
                        "instant_risk_P_A_t": f"{region_risk.probability:.6f}",
                        "future_risk_probability": ""
                        if prediction is None
                        else f"{prediction:.6f}",
                        "alert": ""
                        if prediction is None
                        else int(prediction >= threshold),
                        "window_ready": int(prediction is not None),
                    }
                )
                rows_written += 1

            print_progress(
                frame_id=frame_id,
                total_frames=total_frames,
                rows_written=rows_written,
                detections_count=len(detections),
                start_time=start_time,
            )

            if not args.no_show or video_writer is not None:
                annotated_frame = make_annotated_frame(
                    frame=frame,
                    detections=detections,
                    labels=labels,
                    state_label_blocks=state_label_blocks,
                    source_polygons=source_polygons,
                    region_risks=region_risks,
                    box_annotator=box_annotator,
                    label_annotator=label_annotator,
                    trace_annotator=trace_annotator,
                    text_scale=text_scale,
                    thickness=thickness,
                    show_state_labels=False,
                    vehicle_label_mode="speed",
                )
                annotated_frame = draw_temporal_prediction_blocks(
                    frame=annotated_frame,
                    predictions=predictions,
                    regions=regions,
                    threshold=threshold,
                )
                if use_dashboard:
                    elapsed = max(time.perf_counter() - start_time, 1e-6)
                    annotated_frame = render_traffic_dashboard(
                        annotated_frame=annotated_frame,
                        region_risks=region_risks,
                        vehicle_states=vehicle_states,
                        frame_id=frame_id,
                        timestamp_s=timestamp_s,
                        source_name=source_video_path.stem,
                        processing_fps=(frame_id + 1) / elapsed,
                        dashboard_state=dashboard_state,
                        predictions=predictions,
                        prediction_threshold=threshold,
                        output_size=output_resolution_wh,
                    )

                if video_writer is not None:
                    video_writer.write(annotated_frame)

                if not args.no_show:
                    height, width = annotated_frame.shape[:2]
                    display_height = int(height * args.display_width / width)
                    display_frame = cv2.resize(
                        annotated_frame,
                        (args.display_width, display_height),
                        interpolation=cv2.INTER_AREA,
                    )
                    cv2.imshow("end_to_end_demo", display_frame)
                    if cv2.waitKey(1) & 0xFF == ord("q"):
                        break

    if video_writer is not None:
        video_writer.release()
    if not args.no_show:
        cv2.destroyAllWindows()

    print()
    print(f"Demo predictions saved to: {prediction_csv_path}")
    print(f"Output folder: {output_dir}")


if __name__ == "__main__":
    main()
