import argparse
import json
from datetime import datetime
from pathlib import Path

import numpy as np
import torch
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

from models import build_model


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_MODEL_ROOT = PROJECT_ROOT / "trained_models"


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a PyTorch temporal model for future road risk prediction."
    )
    parser.add_argument(
        "--dataset-dir",
        required=True,
        help="Directory generated by make_dataset.py.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Training output directory. Defaults to trained_models/<timestamp>_<model>.",
    )
    parser.add_argument(
        "--model",
        default="lstm",
        choices=["rnn", "gru", "lstm", "transformer", "mamba"],
        help="Temporal model architecture.",
    )
    parser.add_argument("--hidden-size", default=64, type=int)
    parser.add_argument("--num-layers", default=2, type=int)
    parser.add_argument("--dropout", default=0.1, type=float)
    parser.add_argument("--batch-size", default=64, type=int)
    parser.add_argument("--epochs", default=30, type=int)
    parser.add_argument("--learning-rate", default=1e-3, type=float)
    parser.add_argument("--weight-decay", default=1e-4, type=float)
    parser.add_argument("--threshold", default=0.5, type=float)
    parser.add_argument("--patience", default=8, type=int)
    parser.add_argument("--random-state", default=42, type=int)
    parser.add_argument(
        "--device",
        default="auto",
        choices=["auto", "cpu", "cuda"],
        help="Training device.",
    )
    return parser.parse_args()


def resolve_path(path_text: str) -> Path:
    path = Path(path_text)
    if path.exists():
        return path
    project_path = PROJECT_ROOT / path
    if project_path.exists():
        return project_path
    return path


def create_output_dir(output_dir_text: str | None, model_name: str) -> Path:
    if output_dir_text:
        output_dir = Path(output_dir_text)
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_dir = DEFAULT_MODEL_ROOT / f"{timestamp}_{model_name}_risk"
    output_dir.mkdir(parents=True, exist_ok=False)
    return output_dir


def load_npz(dataset_dir: Path, split: str) -> tuple[np.ndarray, np.ndarray]:
    path = dataset_dir / f"{split}.npz"
    if not path.exists():
        raise FileNotFoundError(f"Missing split file: {path}")
    data = np.load(path)
    return data["X"].astype(np.float32), data["y"].astype(np.float32)


def make_loader(
    X: np.ndarray,
    y: np.ndarray,
    batch_size: int,
    shuffle: bool,
) -> DataLoader:
    dataset = TensorDataset(
        torch.from_numpy(X),
        torch.from_numpy(y).unsqueeze(1),
    )
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)


def choose_device(device_arg: str) -> torch.device:
    if device_arg == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA was requested but is not available.")
        return torch.device("cuda")
    if device_arg == "auto" and torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def evaluate(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    device: torch.device,
    threshold: float,
) -> dict[str, float]:
    model.eval()
    losses = []
    probabilities = []
    targets = []
    with torch.no_grad():
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)
            logits = model(X_batch)
            loss = criterion(logits, y_batch)
            losses.append(float(loss.item()))
            probabilities.extend(torch.sigmoid(logits).cpu().numpy().reshape(-1).tolist())
            targets.extend(y_batch.cpu().numpy().reshape(-1).tolist())

    y_true = np.array(targets, dtype=np.float32)
    y_prob = np.array(probabilities, dtype=np.float32)
    y_pred = (y_prob >= threshold).astype(np.float32)
    metrics = {
        "loss": float(np.mean(losses)) if losses else 0.0,
        "accuracy": float(accuracy_score(y_true, y_pred)) if len(y_true) else 0.0,
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "f1": float(f1_score(y_true, y_pred, zero_division=0)),
    }
    if len(np.unique(y_true)) == 2:
        metrics["auc"] = float(roc_auc_score(y_true, y_prob))
    else:
        metrics["auc"] = 0.0
    return metrics


def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
) -> float:
    model.train()
    losses = []
    for X_batch, y_batch in loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)
        optimizer.zero_grad(set_to_none=True)
        logits = model(X_batch)
        loss = criterion(logits, y_batch)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
        optimizer.step()
        losses.append(float(loss.item()))
    return float(np.mean(losses)) if losses else 0.0


def main() -> None:
    args = parse_arguments()
    torch.manual_seed(args.random_state)
    np.random.seed(args.random_state)

    dataset_dir = resolve_path(args.dataset_dir)
    output_dir = create_output_dir(args.output_dir, args.model)
    with (dataset_dir / "dataset_metadata.json").open("r", encoding="utf-8") as file:
        dataset_metadata = json.load(file)

    X_train, y_train = load_npz(dataset_dir, "train")
    X_val, y_val = load_npz(dataset_dir, "val")
    X_test, y_test = load_npz(dataset_dir, "test")
    input_size = int(X_train.shape[-1])

    device = choose_device(args.device)
    model = build_model(
        name=args.model,
        input_size=input_size,
        hidden_size=args.hidden_size,
        num_layers=args.num_layers,
        dropout=args.dropout,
    ).to(device)

    positive_count = float(y_train.sum())
    negative_count = float(len(y_train) - positive_count)
    pos_weight = torch.tensor(
        [negative_count / max(positive_count, 1.0)],
        dtype=torch.float32,
        device=device,
    )
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.learning_rate,
        weight_decay=args.weight_decay,
    )

    train_loader = make_loader(X_train, y_train, args.batch_size, shuffle=True)
    val_loader = make_loader(X_val, y_val, args.batch_size, shuffle=False)
    test_loader = make_loader(X_test, y_test, args.batch_size, shuffle=False)

    best_val_loss = float("inf")
    best_epoch = 0
    epochs_without_improvement = 0
    history = []
    best_model_path = output_dir / "best_model.pt"

    for epoch in range(1, args.epochs + 1):
        train_loss = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_metrics = evaluate(model, val_loader, criterion, device, args.threshold)
        history_row = {
            "epoch": epoch,
            "train_loss": train_loss,
            **{f"val_{key}": value for key, value in val_metrics.items()},
        }
        history.append(history_row)
        print(
            f"epoch {epoch:03d} | train_loss={train_loss:.4f} | "
            f"val_loss={val_metrics['loss']:.4f} | "
            f"val_f1={val_metrics['f1']:.4f} | val_auc={val_metrics['auc']:.4f}"
        )

        if val_metrics["loss"] < best_val_loss:
            best_val_loss = val_metrics["loss"]
            best_epoch = epoch
            epochs_without_improvement = 0
            torch.save(
                {
                    "model_state_dict": model.state_dict(),
                    "model_name": args.model,
                    "input_size": input_size,
                    "hidden_size": args.hidden_size,
                    "num_layers": args.num_layers,
                    "dropout": args.dropout,
                    "feature_columns": dataset_metadata.get("feature_columns", []),
                    "feature_mean": dataset_metadata.get("feature_mean", []),
                    "feature_std": dataset_metadata.get("feature_std", []),
                    "threshold": args.threshold,
                },
                best_model_path,
            )
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= args.patience:
                print(f"Early stopping at epoch {epoch}.")
                break

    checkpoint = torch.load(best_model_path, map_location=device)
    model.load_state_dict(checkpoint["model_state_dict"])
    test_metrics = evaluate(model, test_loader, criterion, device, args.threshold)

    metadata = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "dataset_dir": str(dataset_dir),
        "model_path": str(best_model_path),
        "model": args.model,
        "input_size": input_size,
        "sequence_length": int(X_train.shape[1]),
        "train_rows": int(len(y_train)),
        "val_rows": int(len(y_val)),
        "test_rows": int(len(y_test)),
        "positive_train_rows": int(y_train.sum()),
        "best_epoch": best_epoch,
        "best_val_loss": best_val_loss,
        "test_metrics": test_metrics,
        "args": vars(args),
    }
    with (output_dir / "training_metadata.json").open("w", encoding="utf-8") as file:
        json.dump(metadata, file, ensure_ascii=False, indent=2)
    with (output_dir / "training_history.json").open("w", encoding="utf-8") as file:
        json.dump(history, file, ensure_ascii=False, indent=2)

    print(f"Best model saved to: {best_model_path}")
    print(f"Test loss: {test_metrics['loss']:.4f}")
    print(f"Test F1: {test_metrics['f1']:.4f}")
    print(f"Test AUC: {test_metrics['auc']:.4f}")


if __name__ == "__main__":
    main()
