import argparse
import json
from datetime import datetime
from pathlib import Path

import matplotlib
import numpy as np
import torch
from sklearn.metrics import (
    accuracy_score,
    auc,
    confusion_matrix,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

from models import build_model


matplotlib.use("Agg")
import matplotlib.pyplot as plt


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_MODEL_ROOT = PROJECT_ROOT / "trained_models"


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a PyTorch temporal model for future road risk prediction."
    )
    parser.add_argument(
        "--dataset-dir",
        required=True,
        help="Directory generated by make_dataset.py.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Training output directory. Defaults to trained_models/<timestamp>_<model>.",
    )
    parser.add_argument(
        "--model",
        default="mtpnet",
        choices=[
            "rnn",
            "gru",
            "lstm",
            "transformer",
            "mamba",
            "mtpnet",
            "mtpnet_no_temporal",
        ],
        help="Temporal model architecture.",
    )
    parser.add_argument("--hidden-size", default=64, type=int)
    parser.add_argument("--num-layers", default=2, type=int)
    parser.add_argument("--dropout", default=0.1, type=float)
    parser.add_argument("--batch-size", default=64, type=int)
    parser.add_argument("--epochs", default=30, type=int)
    parser.add_argument("--learning-rate", default=1e-3, type=float)
    parser.add_argument("--weight-decay", default=1e-4, type=float)
    parser.add_argument("--threshold", default=0.5, type=float)
    parser.add_argument("--patience", default=8, type=int)
    parser.add_argument("--random-state", default=42, type=int)
    parser.add_argument(
        "--device",
        default="auto",
        choices=["auto", "cpu", "cuda"],
        help="Training device.",
    )
    return parser.parse_args()


def resolve_path(path_text: str) -> Path:
    path = Path(path_text)
    if path.exists():
        return path
    project_path = PROJECT_ROOT / path
    if project_path.exists():
        return project_path
    return path


def create_output_dir(output_dir_text: str | None, model_name: str) -> Path:
    if output_dir_text:
        output_dir = Path(output_dir_text)
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_dir = DEFAULT_MODEL_ROOT / f"{timestamp}_{model_name}_risk"
    output_dir.mkdir(parents=True, exist_ok=False)
    return output_dir


def load_npz(dataset_dir: Path, split: str) -> tuple[np.ndarray, np.ndarray]:
    path = dataset_dir / f"{split}.npz"
    if not path.exists():
        raise FileNotFoundError(f"Missing split file: {path}")
    data = np.load(path)
    return data["X"].astype(np.float32), data["y"].astype(np.float32)


def make_loader(
    X: np.ndarray,
    y: np.ndarray,
    batch_size: int,
    shuffle: bool,
) -> DataLoader:
    dataset = TensorDataset(
        torch.from_numpy(X),
        torch.from_numpy(y).unsqueeze(1),
    )
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)


def choose_device(device_arg: str) -> torch.device:
    if device_arg == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA was requested but is not available.")
        return torch.device("cuda")
    if device_arg == "auto" and torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def evaluate(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    device: torch.device,
    threshold: float,
) -> dict[str, float]:
    model.eval()
    losses = []
    probabilities = []
    targets = []
    with torch.no_grad():
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)
            logits = model(X_batch)
            loss = criterion(logits, y_batch)
            losses.append(float(loss.item()))
            probabilities.extend(torch.sigmoid(logits).cpu().numpy().reshape(-1).tolist())
            targets.extend(y_batch.cpu().numpy().reshape(-1).tolist())

    y_true = np.array(targets, dtype=np.float32)
    y_prob = np.array(probabilities, dtype=np.float32)
    y_pred = (y_prob >= threshold).astype(np.float32)
    metrics = {
        "loss": float(np.mean(losses)) if losses else 0.0,
        "accuracy": float(accuracy_score(y_true, y_pred)) if len(y_true) else 0.0,
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "f1": float(f1_score(y_true, y_pred, zero_division=0)),
    }
    if len(np.unique(y_true)) == 2:
        metrics["auc"] = float(roc_auc_score(y_true, y_prob))
    else:
        metrics["auc"] = 0.0
    return metrics


def predict_probabilities(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
) -> tuple[np.ndarray, np.ndarray]:
    model.eval()
    probabilities = []
    targets = []
    with torch.no_grad():
        for X_batch, y_batch in loader:
            logits = model(X_batch.to(device))
            probabilities.extend(torch.sigmoid(logits).cpu().numpy().reshape(-1).tolist())
            targets.extend(y_batch.numpy().reshape(-1).tolist())
    return np.array(targets, dtype=np.float32), np.array(probabilities, dtype=np.float32)


def plot_training_curves(history: list[dict[str, float]], output_dir: Path) -> Path:
    plots_dir = output_dir / "plots"
    plots_dir.mkdir(exist_ok=True)
    epochs = [row["epoch"] for row in history]

    fig, axes = plt.subplots(2, 2, figsize=(14, 9), constrained_layout=True)
    axes[0, 0].plot(epochs, [row["train_loss"] for row in history], label="train")
    axes[0, 0].plot(epochs, [row["val_loss"] for row in history], label="val")
    axes[0, 0].set_title("Loss")
    axes[0, 0].set_xlabel("epoch")
    axes[0, 0].set_ylabel("BCE loss")

    for metric in ["accuracy", "precision", "recall", "f1"]:
        axes[0, 1].plot(
            epochs,
            [row[f"train_{metric}"] for row in history],
            linestyle="--",
            label=f"train {metric}",
        )
        axes[0, 1].plot(
            epochs,
            [row[f"val_{metric}"] for row in history],
            label=f"val {metric}",
        )
    axes[0, 1].set_title("Classification metrics")
    axes[0, 1].set_xlabel("epoch")
    axes[0, 1].set_ylabel("score")

    axes[1, 0].plot(epochs, [row["train_auc"] for row in history], label="train AUC")
    axes[1, 0].plot(epochs, [row["val_auc"] for row in history], label="val AUC")
    axes[1, 0].set_title("ROC AUC")
    axes[1, 0].set_xlabel("epoch")
    axes[1, 0].set_ylabel("AUC")

    axes[1, 1].plot(epochs, [row["train_f1"] for row in history], label="train F1")
    axes[1, 1].plot(epochs, [row["val_f1"] for row in history], label="val F1")
    axes[1, 1].set_title("F1")
    axes[1, 1].set_xlabel("epoch")
    axes[1, 1].set_ylabel("F1")

    for axis in axes.ravel():
        axis.grid(True, alpha=0.3)
        axis.legend(fontsize=8)

    path = plots_dir / "training_curves.png"
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return path


def plot_test_classification_figures(
    y_true: np.ndarray,
    y_prob: np.ndarray,
    threshold: float,
    output_dir: Path,
) -> list[Path]:
    plots_dir = output_dir / "plots"
    plots_dir.mkdir(exist_ok=True)
    saved_paths = []
    y_pred = (y_prob >= threshold).astype(np.float32)

    matrix = confusion_matrix(y_true, y_pred, labels=[0, 1])
    fig, axis = plt.subplots(figsize=(5.5, 5), constrained_layout=True)
    image = axis.imshow(matrix, cmap="Blues")
    axis.set_title("Confusion matrix")
    axis.set_xlabel("predicted")
    axis.set_ylabel("true")
    axis.set_xticks([0, 1], labels=["normal", "high risk"])
    axis.set_yticks([0, 1], labels=["normal", "high risk"])
    for row in range(matrix.shape[0]):
        for col in range(matrix.shape[1]):
            axis.text(col, row, str(matrix[row, col]), ha="center", va="center")
    fig.colorbar(image, ax=axis)
    path = plots_dir / "confusion_matrix.png"
    fig.savefig(path, dpi=160)
    plt.close(fig)
    saved_paths.append(path)

    if len(np.unique(y_true)) == 2:
        fpr, tpr, _ = roc_curve(y_true, y_prob)
        fig, axis = plt.subplots(figsize=(6, 5), constrained_layout=True)
        axis.plot(fpr, tpr, label=f"AUC = {auc(fpr, tpr):.3f}")
        axis.plot([0, 1], [0, 1], linestyle="--", color="gray")
        axis.set_title("ROC curve")
        axis.set_xlabel("false positive rate")
        axis.set_ylabel("true positive rate")
        axis.grid(True, alpha=0.3)
        axis.legend()
        path = plots_dir / "roc_curve.png"
        fig.savefig(path, dpi=160)
        plt.close(fig)
        saved_paths.append(path)

        precision, recall, _ = precision_recall_curve(y_true, y_prob)
        fig, axis = plt.subplots(figsize=(6, 5), constrained_layout=True)
        axis.plot(recall, precision, label=f"PR AUC = {auc(recall, precision):.3f}")
        axis.set_title("Precision-recall curve")
        axis.set_xlabel("recall")
        axis.set_ylabel("precision")
        axis.grid(True, alpha=0.3)
        axis.legend()
        path = plots_dir / "precision_recall_curve.png"
        fig.savefig(path, dpi=160)
        plt.close(fig)
        saved_paths.append(path)

    fig, axis = plt.subplots(figsize=(7, 5), constrained_layout=True)
    axis.hist(y_prob[y_true == 0], bins=20, alpha=0.7, label="normal")
    axis.hist(y_prob[y_true == 1], bins=20, alpha=0.7, label="high risk")
    axis.axvline(threshold, color="black", linestyle="--", label="threshold")
    axis.set_title("Predicted probability histogram")
    axis.set_xlabel("predicted high-risk probability")
    axis.set_ylabel("count")
    axis.grid(True, alpha=0.3)
    axis.legend()
    path = plots_dir / "probability_histogram.png"
    fig.savefig(path, dpi=160)
    plt.close(fig)
    saved_paths.append(path)

    return saved_paths


def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
) -> float:
    model.train()
    losses = []
    for X_batch, y_batch in loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)
        optimizer.zero_grad(set_to_none=True)
        logits = model(X_batch)
        loss = criterion(logits, y_batch)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
        optimizer.step()
        losses.append(float(loss.item()))
    return float(np.mean(losses)) if losses else 0.0


def main() -> None:
    args = parse_arguments()
    torch.manual_seed(args.random_state)
    np.random.seed(args.random_state)

    dataset_dir = resolve_path(args.dataset_dir)
    output_dir = create_output_dir(args.output_dir, args.model)
    with (dataset_dir / "dataset_metadata.json").open("r", encoding="utf-8") as file:
        dataset_metadata = json.load(file)

    X_train, y_train = load_npz(dataset_dir, "train")
    X_val, y_val = load_npz(dataset_dir, "val")
    X_test, y_test = load_npz(dataset_dir, "test")
    input_size = int(X_train.shape[-1])

    device = choose_device(args.device)
    model = build_model(
        name=args.model,
        input_size=input_size,
        hidden_size=args.hidden_size,
        num_layers=args.num_layers,
        dropout=args.dropout,
    ).to(device)

    positive_count = float(y_train.sum())
    negative_count = float(len(y_train) - positive_count)
    pos_weight = torch.tensor(
        [negative_count / max(positive_count, 1.0)],
        dtype=torch.float32,
        device=device,
    )
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.learning_rate,
        weight_decay=args.weight_decay,
    )

    train_loader = make_loader(X_train, y_train, args.batch_size, shuffle=True)
    val_loader = make_loader(X_val, y_val, args.batch_size, shuffle=False)
    test_loader = make_loader(X_test, y_test, args.batch_size, shuffle=False)

    best_val_loss = float("inf")
    best_epoch = 0
    epochs_without_improvement = 0
    history = []
    best_model_path = output_dir / "best_model.pt"

    for epoch in range(1, args.epochs + 1):
        train_loss = train_one_epoch(model, train_loader, criterion, optimizer, device)
        train_metrics = evaluate(model, train_loader, criterion, device, args.threshold)
        val_metrics = evaluate(model, val_loader, criterion, device, args.threshold)
        history_row = {
            "epoch": epoch,
            "train_loss": train_loss,
            **{f"train_{key}": value for key, value in train_metrics.items()},
            **{f"val_{key}": value for key, value in val_metrics.items()},
        }
        history_row["train_loss"] = train_loss
        history.append(history_row)
        print(
            f"epoch {epoch:03d} | train_loss={train_loss:.4f} | "
            f"train_f1={train_metrics['f1']:.4f} | "
            f"val_loss={val_metrics['loss']:.4f} | "
            f"val_f1={val_metrics['f1']:.4f} | val_auc={val_metrics['auc']:.4f}"
        )

        if val_metrics["loss"] < best_val_loss:
            best_val_loss = val_metrics["loss"]
            best_epoch = epoch
            epochs_without_improvement = 0
            torch.save(
                {
                    "model_state_dict": model.state_dict(),
                    "model_name": args.model,
                    "input_size": input_size,
                    "hidden_size": args.hidden_size,
                    "num_layers": args.num_layers,
                    "dropout": args.dropout,
                    "feature_columns": dataset_metadata.get("feature_columns", []),
                    "feature_mean": dataset_metadata.get("feature_mean", []),
                    "feature_std": dataset_metadata.get("feature_std", []),
                    "threshold": args.threshold,
                },
                best_model_path,
            )
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= args.patience:
                print(f"Early stopping at epoch {epoch}.")
                break

    checkpoint = torch.load(best_model_path, map_location=device)
    model.load_state_dict(checkpoint["model_state_dict"])
    test_metrics = evaluate(model, test_loader, criterion, device, args.threshold)
    y_test_true, y_test_prob = predict_probabilities(model, test_loader, device)
    plot_paths = [plot_training_curves(history, output_dir)]
    plot_paths.extend(
        plot_test_classification_figures(
            y_true=y_test_true,
            y_prob=y_test_prob,
            threshold=args.threshold,
            output_dir=output_dir,
        )
    )

    metadata = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "dataset_dir": str(dataset_dir),
        "model_path": str(best_model_path),
        "model": args.model,
        "input_size": input_size,
        "sequence_length": int(X_train.shape[1]),
        "train_rows": int(len(y_train)),
        "val_rows": int(len(y_val)),
        "test_rows": int(len(y_test)),
        "positive_train_rows": int(y_train.sum()),
        "best_epoch": best_epoch,
        "best_val_loss": best_val_loss,
        "test_metrics": test_metrics,
        "plot_paths": [str(path) for path in plot_paths],
        "args": vars(args),
    }
    with (output_dir / "training_metadata.json").open("w", encoding="utf-8") as file:
        json.dump(metadata, file, ensure_ascii=False, indent=2)
    with (output_dir / "training_history.json").open("w", encoding="utf-8") as file:
        json.dump(history, file, ensure_ascii=False, indent=2)

    print(f"Best model saved to: {best_model_path}")
    print(f"Plots saved to: {output_dir / 'plots'}")
    print(f"Test loss: {test_metrics['loss']:.4f}")
    print(f"Test F1: {test_metrics['f1']:.4f}")
    print(f"Test AUC: {test_metrics['auc']:.4f}")


if __name__ == "__main__":
    main()
