import argparse
import json
from datetime import datetime
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler


PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_MODEL_ROOT = PROJECT_ROOT / "models"
DEFAULT_FEATURE_COLUMNS = [
    "vehicle_type",
    "timestamp_s",
    "track_age_s",
    "track_age_frames",
    "road_x_m",
    "road_y_m",
    "distance_to_stopline_m",
    "speed_mps",
    "speed_kmh",
    "smoothed_speed_mps",
    "acceleration_mps2",
    "delta_speed_mps",
    "bbox_width",
    "bbox_height",
    "bbox_area",
    "bbox_aspect_ratio",
    "confidence",
    "red_light_phase",
    "in_observation_zone",
]


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train an ML model from cleaned vehicle trajectory datasets."
    )
    parser.add_argument(
        "--dataset-path",
        required=True,
        help="Path to dataset.csv generated by make_dataset.py.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Model output directory. Defaults to models/<timestamp>_brake_model.",
    )
    parser.add_argument(
        "--target-column",
        default="required_braking_distance_m",
        help="Regression target column.",
    )
    parser.add_argument(
        "--test-size",
        default=0.2,
        type=float,
        help="Validation split ratio.",
    )
    parser.add_argument(
        "--random-state",
        default=42,
        type=int,
        help="Random seed.",
    )
    parser.add_argument(
        "--n-estimators",
        default=300,
        type=int,
        help="Number of trees for RandomForestRegressor.",
    )
    parser.add_argument(
        "--max-depth",
        default=None,
        type=int,
        help="Optional max tree depth.",
    )
    parser.add_argument(
        "--n-jobs",
        default=1,
        type=int,
        help="Parallel jobs for RandomForestRegressor. Use -1 on unrestricted machines.",
    )
    return parser.parse_args()


def resolve_path(path_text: str) -> Path:
    path = Path(path_text)
    if path.exists():
        return path
    project_path = PROJECT_ROOT / path
    if project_path.exists():
        return project_path
    return path


def create_output_dir(output_dir_text: str | None) -> Path:
    if output_dir_text:
        output_dir = Path(output_dir_text)
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_dir = DEFAULT_MODEL_ROOT / f"{timestamp}_brake_model"
    output_dir.mkdir(parents=True, exist_ok=False)
    return output_dir


def load_feature_columns(dataset_path: Path, df: pd.DataFrame) -> list[str]:
    feature_path = dataset_path.parent / "feature_columns.json"
    if feature_path.exists():
        with feature_path.open("r", encoding="utf-8") as file:
            columns = json.load(file)
    else:
        columns = DEFAULT_FEATURE_COLUMNS
    return [column for column in columns if column in df.columns]


def build_pipeline(
    feature_columns: list[str],
    categorical_columns: list[str],
    args: argparse.Namespace,
) -> Pipeline:
    numeric_columns = [
        column for column in feature_columns if column not in categorical_columns
    ]
    preprocessor = ColumnTransformer(
        transformers=[
            (
                "numeric",
                Pipeline(
                    steps=[
                        ("imputer", SimpleImputer(strategy="median")),
                        ("scaler", StandardScaler()),
                    ]
                ),
                numeric_columns,
            ),
            (
                "categorical",
                Pipeline(
                    steps=[
                        ("imputer", SimpleImputer(strategy="most_frequent")),
                        ("onehot", OneHotEncoder(handle_unknown="ignore")),
                    ]
                ),
                categorical_columns,
            ),
        ]
    )
    model = RandomForestRegressor(
        n_estimators=args.n_estimators,
        max_depth=args.max_depth,
        random_state=args.random_state,
        n_jobs=args.n_jobs,
    )
    return Pipeline(steps=[("preprocessor", preprocessor), ("model", model)])


def regression_metrics(y_true: pd.Series, y_pred: np.ndarray) -> dict[str, float]:
    mse = mean_squared_error(y_true, y_pred)
    return {
        "mae": float(mean_absolute_error(y_true, y_pred)),
        "rmse": float(np.sqrt(mse)),
        "r2": float(r2_score(y_true, y_pred)),
    }


def main() -> None:
    args = parse_arguments()
    dataset_path = resolve_path(args.dataset_path)
    if not dataset_path.exists():
        raise FileNotFoundError(f"Dataset not found: {dataset_path}")

    output_dir = create_output_dir(args.output_dir)
    df = pd.read_csv(dataset_path, encoding="utf-8-sig")
    if args.target_column not in df.columns:
        raise ValueError(f"Target column not found: {args.target_column}")

    feature_columns = load_feature_columns(dataset_path, df)
    if not feature_columns:
        raise ValueError("No usable feature columns found.")

    training_df = df.dropna(subset=[args.target_column]).copy()
    X = training_df[feature_columns]
    y = pd.to_numeric(training_df[args.target_column], errors="coerce")
    valid_target = y.notna()
    X = X[valid_target]
    y = y[valid_target]
    if len(y) < 10:
        raise ValueError("Need at least 10 valid training rows.")

    categorical_columns = [
        column for column in ["vehicle_type"] if column in feature_columns
    ]
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=args.test_size,
        random_state=args.random_state,
    )

    pipeline = build_pipeline(feature_columns, categorical_columns, args)
    pipeline.fit(X_train, y_train)

    train_pred = pipeline.predict(X_train)
    test_pred = pipeline.predict(X_test)
    metrics = {
        "train": regression_metrics(y_train, train_pred),
        "test": regression_metrics(y_test, test_pred),
    }

    model_path = output_dir / "brake_distance_model.joblib"
    joblib.dump(pipeline, model_path)

    predictions = X_test.copy()
    predictions[args.target_column] = y_test.values
    predictions["prediction"] = test_pred
    predictions["absolute_error"] = np.abs(predictions[args.target_column] - test_pred)
    predictions.to_csv(
        output_dir / "validation_predictions.csv",
        index=False,
        encoding="utf-8-sig",
    )

    metadata = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "dataset_path": str(dataset_path),
        "target_column": args.target_column,
        "feature_columns": feature_columns,
        "categorical_columns": categorical_columns,
        "rows": int(len(y)),
        "train_rows": int(len(y_train)),
        "test_rows": int(len(y_test)),
        "model_path": str(model_path),
        "metrics": metrics,
        "args": vars(args),
    }
    with (output_dir / "training_metadata.json").open("w", encoding="utf-8") as file:
        json.dump(metadata, file, ensure_ascii=False, indent=2)

    print(f"Model saved to: {model_path}")
    print(f"Metrics saved to: {output_dir / 'training_metadata.json'}")
    print(f"Test MAE: {metrics['test']['mae']:.3f}")
    print(f"Test RMSE: {metrics['test']['rmse']:.3f}")
    print(f"Test R2: {metrics['test']['r2']:.3f}")


if __name__ == "__main__":
    main()
